package com.enterprisex.wallsofwonder.oms.Enums;

public enum OrderStatus {
    PENDING_CONFIRMATION("PENDING_CONFIRMATION"),
    PENDING_PAYMENT("PENDING_PAYMENT"),
    PENDING_COD_VERIFICATION("PENDING_COD_VERIFICATION"),
    PAYMENT_ERROR("PAYMENT_ERROR"),
    PENDING("PENDING"),

    CONFIRMED("CONFIRMED"),
    PAYMENT_VERIFIED("PAYMENT_VERIFIED"),
    COD_VERIFIED("COD_VERIFIED"),
    PICKLIST_GENERATED("PICKLIST_GENERATED"),
    PUSHED_TO_ERP("PUSHED_TO_ERP"),
    ERROR_IN_PUSH_TO_ERP("ERROR_IN_PUSH_TO_ERP"),
    PROCESSING("PROCESSING"),
    PICKED("PICKED"),
    PACKED("PACKED"),


    CANCELLED("CANCELLED"),
    CANCELLED_BY_ADMIN("CANCELLED_BY_ADMIN"),
    REFUND_ERROR("REFUND_ERROR"),
    CANCEL_INITIATED("CANCEL_INITIATED"),
    CANCEL_ERROR("CANCEL_ERROR"),
    CANCEL_PUSHED_TO_ERP("CANCEL_PUSHED_TO_ERP"),
    ERROR_IN_CANCEL_PUSHED_TO_ERP("ERROR_IN_CANCEL_PUSHED_TO_ERP"),

    ON_HOLD("ON_HOLD"),

    REFUSED("REFUSED"),

    DISPATCHED("DISPATCHED"),

    DELIVERED("DELIVERED"),


    RETURN_REQUESTED("RETURN_REQUESTED"),
    RETURN_APPROVED("RETURN_APPROVED"),
    AWAITING_RETURN("AWAITING_RETURN"),
    RETURNED("RETURNED"),
    REFUNDED("REFUNDED"),


    UNREACHED("UNREACHED");

    private final String code;

    OrderStatus(String code) {
        this.code = code;
    }

    public String getCode() {
        return this.code;
    }

}
